### ISSUE TITLE
Setup an an demo on one of the LTRC servers which is in sync with the repository

### ISSUE THREAD

**Issue by spMohanty** [spMohanty/TranslatorsDesk#14]
@mrinaldhar : Can you talk to Rashid sir and setup the demo of the TranslatorsDesk somewhere stable ? I think @nehal can help you get access to some server in ltrc where you can host this, if Rashid sir is not available. 

At the end of it, you could let a cronjob running, which keeps the code in the demo in sync with this repository.

This is important as Dipti Mam and Manish Sir are not being able to check the system and any of the new features.

**Comment by mrinaldhar** [comment]
I tried installing the requirements on the ltrc server, but it threw an error: http://pastebin.com/Xi4fhDCA

I haven't tried to look into what might be causing the error yet, I'll check it out.

**Comment by mrinaldhar** [comment]
I got all other modules to install on the LTRC server, but for some reason, aspell module just wont install. Here's the exact error: http://pastebin.com/5ueATgRM

Any suggestions?

**Comment by mrinaldhar** [comment]
Further localized the problem to missing packages for hindi, and other languages (except English). The above error is now resolved.

**Comment by mrinaldhar** [comment]
Installed all dictionaries needed, on the LTRC server by downloading directly from a mirror. It runs now. 

I'll update the readme with the instructions for CentOS. And set this up to be accessible via apache.

**Comment by m-chanakya** [comment]
Resolved.
